apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-as-root
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: run-as-root
  template:
    metadata:
      labels:
        app: run-as-root
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          command: ["sh", "-c", "sleep 3600"]
          securityContext:
            runAsGroup: 0        # run as root
            allowPrivilegeEscalation: false

