apiVersion: v1
kind: Pod
metadata:
  name: other-pod
  annotations:
    other: "2"
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: other
          value: "2"
